Adiciona parâmetros da github action na documentação
betrybe/cypress-evaluator-action pull request #10
Opened 2020-11-25 19:16 UTC by jeanpsv

Adiciona documentação para os parâmetros existentes na GitHub Action

2020-11-25 20:00 UTC, LeandroLM approved these changes

2020-11-25 21:53 UTC, inaC requested changes

2020-11-25 21:53 UTC, inaC commented on README.md
> +The project that want to use this action should implement unit tests grouping them using `describe` statements.
```suggestion
The project that wants to use this action should implement unit tests grouping them using `describe` statements.
```

2020-11-25 21:53 UTC, inaC commented on README.md
>  ## Project contraints
```suggestion
## Project constraints
```

2020-11-25 21:53 UTC, inaC commented on README.md
> +Each `describe` statement will be mapped to a requirement.
Vale a pena destacar, porque isso já foi motivo de confusão
```suggestion
Each `describe` statement **will be mapped to a requirement**. 
```

2020-11-26 17:09 UTC, jeanpsv commented
@inaC 🧑‍🏫 🏴󠁧󠁢󠁥󠁮󠁧󠁿

2020-11-26 17:48 UTC, inaC commented
> @inaC 🧑‍🏫 🏴󠁧󠁢󠁥󠁮󠁧󠁿

🏴󠁧󠁢󠁥󠁮󠁧󠁿 🏴󠁧󠁢󠁥󠁮󠁧󠁿 🏴󠁧󠁢󠁥󠁮󠁧󠁿 🏴󠁧󠁢󠁥󠁮󠁧󠁿 🏴󠁧󠁢󠁥󠁮󠁧󠁿

2020-11-26 17:49 UTC, inaC approved these changes

2020-11-26 20:40 UTC, eucleciojosias approved these changes

2020-11-27 11:25 UTC, merged