imp: recebe username como input
betrybe/cypress-evaluator-action pull request #12
Opened 2021-01-22 20:07 UTC by eucleciojosias

Devido as alterações na [LEARN-869](https://trybe.atlassian.net/browse/LEARN-869?atlOrigin=eyJpIjoiNjk5MjBkZDIzNTM2NDY5NmExMGJjYmRjN2NlZDAzYjAiLCJwIjoiaiJ9) e como o _workflow_ é disparado via **Github App Selfhosted**, a envvar `GITHUB_ACTOR` não poderá ser usada para pegar o **username** da pessoa estudante. Além disso, o **número** da Pull Request não vem no contexto do evento da _action_. Foi modificado para estes dados serem enviados pelo Github App via _input_. Assim sendo, será necessário modificar os avaliadores para o novo formato.

2021-01-25 17:58 UTC, jeanpsv approved these changes

2021-01-26 17:26 UTC, inaC requested changes

2021-01-26 17:26 UTC, inaC commented on README.md
> +### `pr_author_username:
Seria interessante atualizar em como consumir a action com esse novo input obrigatório, nas seções [Simple usage example](https://github.com/betrybe/cypress-evaluator-action#simple-usage-example) e [`How to get result output`](https://github.com/betrybe/cypress-evaluator-action#how-to-get-result-output), não?

2021-01-26 19:03 UTC, inaC approved these changes

2021-02-01 22:42 UTC, merged